// Managed-region and platform-adaptation helpers for `orbit sync`.
//
// Ownership model:
// - Skill bodies are PROJECT-owned. The canonical copy of every skill lives in
//   `.claude/skills/<id>/SKILL.md`; sync derives the other platform copies from it with
//   deterministic transforms (see platformizeBody). Sync never rewrites the canonical copy.
// - Agent files: the frontmatter (markdown) / header keys (TOML) are HARNESS-owned and are
//   regenerated from the capability presets + model config; the body is project-owned except
//   for explicit managed blocks.
// - Managed blocks are wrapped in `<!-- orbit:managed:<name>:start -->` ... `:end -->` markers.
//   Sync rewrites ONLY what is between the markers; everything outside belongs to the project.

export function managedStart(name) {
  return `<!-- orbit:managed:${name}:start -->`;
}

export function managedEnd(name) {
  return `<!-- orbit:managed:${name}:end -->`;
}

export function hasManagedBlock(text, name) {
  return text.includes(managedStart(name)) && text.includes(managedEnd(name));
}

// Inner content between the markers (exclusive), or null when the block is absent/malformed.
export function extractManagedBlock(text, name) {
  const start = text.indexOf(managedStart(name));
  const end = text.indexOf(managedEnd(name));
  if (start === -1 || end === -1 || end < start) {
    return null;
  }
  const innerStart = start + managedStart(name).length;
  return text.slice(innerStart, end).replace(/^\n/, "").replace(/\n$/, "");
}

// Replace the inner content of a managed block. Returns the new text, or null when the block
// is absent (sync leaves the file alone in that case; migration inserts the markers once).
export function replaceManagedBlock(text, name, inner) {
  const start = text.indexOf(managedStart(name));
  const end = text.indexOf(managedEnd(name));
  if (start === -1 || end === -1 || end < start) {
    return null;
  }
  const innerStart = start + managedStart(name).length;
  return `${text.slice(0, innerStart)}\n${inner}\n${text.slice(end)}`;
}

// A full managed block, for templates and migrations that install one from scratch.
export function renderManagedBlock(name, inner) {
  return `${managedStart(name)}\n${inner}\n${managedEnd(name)}`;
}

const MANAGED_ROUTING_NOTE =
  "(Generated by `orbit sync` from skill frontmatter `paths`/`when_to_use`. Do not edit between the markers; edit the skill frontmatter and re-run `orbit sync`.)";

// Platform adaptation applied when deriving a non-Claude copy from the canonical Claude body.
// - Claude Code invokes OpenSpec slash commands with a colon (/opsx:apply); Cursor, OpenCode,
//   and Codex use a hyphen (/opsx-apply).
// - Claude Code reads CLAUDE.md (which imports AGENTS.md); the other platforms read AGENTS.md.
export function platformizeBody(text, platform) {
  if (platform === "claude") {
    return text;
  }
  return text.replace(/\/opsx:([a-z-]+)/g, "/opsx-$1").replace(/CLAUDE\.md/g, "AGENTS.md");
}

// Render the builder routing table from skill records. Records carry the frontmatter metadata
// (id, path_globs, when_to_use, orbit_type); only routable skills appear — the orchestrator
// entrypoint, delegated roles, and skills with no routing metadata are excluded.
export function renderBuilderRoutingRows(records) {
  const routable = records
    .filter((record) => record.kind !== "agent")
    .filter((record) => record.orbit_type !== "orbit-entrypoint")
    .filter((record) => record.path_globs || record.when_to_use)
    .sort((a, b) => a.id.localeCompare(b.id));

  const seen = new Set();
  const rows = [];
  for (const record of routable) {
    if (seen.has(record.id)) {
      continue;
    }
    seen.add(record.id);

    const condition = [record.path_globs, record.when_to_use].filter(Boolean).join(" — ");
    rows.push(`- ${condition} -> \`${record.id}\``);
  }

  if (rows.length === 0) {
    rows.push("- (no routable skills registered yet — add `paths`/`when_to_use` frontmatter and run `orbit sync`)");
  }

  return `${MANAGED_ROUTING_NOTE}\n\n${rows.join("\n")}`;
}

// Split a markdown file into its YAML frontmatter and body. Returns null when the file has no
// leading frontmatter block.
export function splitMarkdownFrontmatter(text) {
  if (!text.startsWith("---\n")) {
    return null;
  }
  const end = text.indexOf("\n---", 4);
  if (end === -1) {
    return null;
  }
  const afterDelimiter = text.indexOf("\n", end + 1);
  return {
    frontmatter: text.slice(0, afterDelimiter === -1 ? text.length : afterDelimiter + 1),
    body: afterDelimiter === -1 ? "" : text.slice(afterDelimiter + 1),
  };
}

// Split a Codex agent TOML file into its header keys and the developer_instructions body.
// Returns null when the file does not follow the generated shape.
const CODEX_BODY_OPEN = "developer_instructions = '''\n";

export function splitCodexAgent(text) {
  const open = text.indexOf(CODEX_BODY_OPEN);
  if (open === -1) {
    return null;
  }
  const bodyStart = open + CODEX_BODY_OPEN.length;
  const close = text.lastIndexOf("\n'''");
  if (close === -1 || close < bodyStart) {
    return null;
  }
  return {
    header: text.slice(0, open),
    body: text.slice(bodyStart, close),
  };
}

export function joinCodexAgent(header, body) {
  return `${header}${CODEX_BODY_OPEN}${body}\n'''\n`;
}
