// Skill-record model shared by `orbit sync` (writer) and `orbit doctor` (checker).
//
// A record is one skill/agent on one platform:
//   { id, tool, kind: "skill"|"agent", path, name, description, when_to_use, orbit_type, path_globs }
//
// Records are built from the single source of truth: the canonical `.claude/skills/*/SKILL.md`
// frontmatter for skills, and the ORBIT_SKILLS definitions for delegated roles. The index and
// the registry JSON are rendered from these records — never hand-edited.

import { ORBIT_SKILLS, PLATFORM_SKILL_DIRS, isSubagentFor, locationFor } from "./skills.js";

// OpenSpec owns its own skills (installed and updated by `openspec init`); Orbit must not
// propagate, index, or overwrite them.
export const EXCLUDED_SKILL_PREFIXES = ["openspec-"];

export function isExcludedSkillId(id) {
  return EXCLUDED_SKILL_PREFIXES.some((prefix) => id.startsWith(prefix));
}

// Minimal YAML frontmatter reader (flat `key: value` scalars — the shape Orbit emits).
export function parseFrontmatter(text) {
  if (!text.startsWith("---")) {
    return {};
  }

  const end = text.indexOf("\n---", 3);
  if (end === -1) {
    return {};
  }

  const frontmatter = text.slice(3, end).trim();
  const metadata = {};

  for (const line of frontmatter.split(/\r?\n/)) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (match) {
      metadata[match[1]] = match[2].trim();
    }
  }

  return metadata;
}

// Build per-platform records for canonical skills ({id, meta}) plus the delegated roles.
export function buildRecords(canonicalSkills, tools) {
  const records = [];

  for (const skill of canonicalSkills) {
    for (const tool of tools) {
      const dir = PLATFORM_SKILL_DIRS[tool];
      if (!dir) {
        continue;
      }
      records.push({
        id: skill.id,
        tool,
        kind: "skill",
        path: `${dir}/${skill.id}/SKILL.md`,
        name: skill.meta.name || skill.id,
        description: skill.meta.description || "",
        when_to_use: skill.meta.when_to_use || "",
        orbit_type: skill.meta.orbit_type || "project-skill",
        path_globs: skill.meta.paths || "",
      });
    }
  }

  for (const role of ORBIT_SKILLS.filter((s) => s.delegation === "subagent")) {
    for (const tool of tools) {
      if (!isSubagentFor(role, tool)) {
        continue;
      }
      records.push({
        id: role.id,
        tool,
        kind: "agent",
        path: locationFor(role, tool).path,
        name: role.id,
        description: role.summary,
        when_to_use: role.useWhen.join("; "),
        orbit_type: role.type,
        path_globs: (role.pathGlobs || []).join(", "),
      });
    }
  }

  return sortRecords(records, tools);
}

// Stable ordering: orchestrator entrypoint first, delegated roles next, project skills last;
// alphabetical within a group; platform order matches the configured tools list.
const TYPE_PRIORITY = { "orbit-entrypoint": 0, "orbit-agent-role": 1 };

export function sortRecords(records, tools) {
  const toolIndex = new Map(tools.map((tool, index) => [tool, index]));
  return [...records].sort((a, b) => {
    const pa = TYPE_PRIORITY[a.orbit_type] ?? 2;
    const pb = TYPE_PRIORITY[b.orbit_type] ?? 2;
    if (pa !== pb) return pa - pb;
    if (a.id !== b.id) return a.id.localeCompare(b.id);
    return (toolIndex.get(a.tool) ?? 99) - (toolIndex.get(b.tool) ?? 99);
  });
}

export function renderRegistry(records) {
  return `${JSON.stringify({ skills: records }, null, 2)}\n`;
}

export function renderIndex(records) {
  const byId = new Map();

  for (const record of records) {
    if (!byId.has(record.id)) {
      byId.set(record.id, []);
    }
    byId.get(record.id).push(record);
  }

  const sections = [];
  for (const [id, skillRecords] of byId.entries()) {
    const first = skillRecords[0];
    const delegation = skillRecords.some((record) => record.kind === "agent") ? "subagent" : "skill";
    const lines = [
      `## ${id}`,
      "",
      `- type: ${first.orbit_type}`,
      `- delegation: ${delegation}`,
      `- summary: ${first.description || "No description provided."}`,
      `- use_when: ${first.when_to_use || "not specified"}`,
    ];

    if (first.path_globs) {
      lines.push(`- path_globs: ${first.path_globs}`);
    }

    lines.push("- paths:");
    for (const record of skillRecords) {
      const tag = record.kind === "agent" ? " (subagent)" : "";
      lines.push(`  - ${record.tool}: ${record.path}${tag}`);
    }

    lines.push("- invocation:");
    for (const record of skillRecords) {
      lines.push(`  - ${record.tool}: ${invocationFor(record.tool, id, record.kind)}`);
    }

    sections.push(lines.join("\n"));
  }

  return `# Orbit Skill Index

This file is discovery metadata only, generated by \`orbit sync\` from skill frontmatter — do not
hand-edit it. Do not treat it as the body of every skill: open a full \`SKILL.md\` only when the
task requires it.

${sections.join("\n\n")}
`;
}

function invocationFor(tool, id, kind) {
  if (kind === "agent") {
    if (tool === "opencode") return `@${id}`;
    if (tool === "cursor") return `/${id}`;
    if (tool === "codex") return `ask Codex to spawn the ${id} agent`;
    return `delegate to the ${id} subagent`;
  }
  return tool === "codex" ? `$${id}` : `/${id}`;
}
